export const MisAlumnos = '/listado-alumnos';
export const NuevoAlumno = '/nuevo-alumno';
export const DarAltaAlumno = '/dar-alta-alumno';
export const MisPlanes = '/planes';
export const IniciarSesion = '/login';
export const DetalleAlumno = '/detalle-alumno';
export const ListadoCuotas = '/listado-cuotas';
export const MisTurnos = '/turnos';
export const getEditarEstudianteStep = (step: number | string) => `/editar-estudiante/${step}`;
export const Calendario = '/calendar';
export const RecuperarContraseña = '/recuperar-contrasena';
export const VerificarCodigo = '/verificar-codigo';
export const ModificarContraseña = '/modificar-contrasena';
